### ISSUE TITLE
Examples for testing page

### ISSUE THREAD

**Issue by pyoneerC** [Eisenwave/cdecl-plus#22]
As an idea, I'd suggest adding the possibility for seeing some examples and how the page works, like by clicking in a box copies the text of that on the main box so we can see complex results to see what's the page is really capable of, can be great addition. 

Such as (imagine you click this in a box in the page and show this:

https://cdecl.plus/?q=_Atomic%20int%20(*(*awoo)%5B%5D)(int%5B*%5D),%20chan

**Comment by Eisenwave** [comment]
Good idea, it's been on the back of my mind already.
